
name: DartFile

on:
  push:
    tags:
      - '*-RC'
      - '[0-9]+.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      - name: Build APK for Firebase
        if: endsWith(github.ref, '-RC')
        run: flutter build apk --debug

      - name: Upload to Firebase
        if: endsWith(github.ref, '-RC')
        run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-debug.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --groups testers

      - name: Build AAB for Play Store
        if: startsWith(github.ref, 'refs/tags/') && !endsWith(github.ref, '-RC')
        run: flutter build appbundle --release

      - name: Upload AAB to Play Store
        if: startsWith(github.ref, 'refs/tags/') && !endsWith(github.ref, '-RC')
        run: |
          cd android
          bundle install
          fastlane upload_internal